package runtime

import (
	"context"
	"time"
)

// JobCreateRequest is passed by the Runtime to JobClient.Create.
// It extends AttemptRequest with Runtime-assigned fields derived from namingSalt.
// The JobClient does not need to know namingSalt.
type JobCreateRequest struct {
	AttemptRequest

	// JobName is the unique backend resource name assigned by the Runtime.
	// The JobClient must use this name verbatim.
	//
	// Properties:
	//   - Opaque: must not expose RunID, NodeID, or other JUMI identifiers.
	//   - Deterministic: same AttemptID always produces the same JobName across
	//     retries and process restarts.
	//     Formula: "spw-" + hex(sha256(namingSalt + attemptID))[:32]
	//
	// A namingSalt that changes on restart breaks crash recovery: the same AttemptID
	// produces a different JobName and the orphaned K8s Job can never be reclaimed.
	JobName string

	// Namespace must also be deterministic for the same AttemptID.
	// If Namespace changes between retries, AlreadyExists detection fails
	// and a duplicate job leaks.
	Namespace string

	// AttemptMarker is an opaque stable ownership token generated by the Runtime.
	// Formula: hex(sha256(namingSalt + attemptID))
	//
	// The JobClient must:
	//   1. Store AttemptMarker as label "spawner.io/attempt-marker" on creation.
	//   2. On AlreadyExists: compare stored marker with req.AttemptMarker.
	//      Same marker  → return existing BackendRef (safe retry).
	//      Diff marker  → return ErrJobConflict (different owner).
	//
	// The JobClient does NOT compute AttemptMarker and does NOT need namingSalt.
	AttemptMarker string
}

// JobEvent is a single state transition observed from a running job.
type JobEvent struct {
	State   AttemptState
	Message string
	// Reason is machine-readable (see Reason* constants).
	// Non-empty on terminal states and on Pending with a known sub-cause.
	Reason    string
	Timestamp time.Time
}

// JobWatchError represents an error that occurs asynchronously after Watch() returns.
type JobWatchError struct {
	Reason  string
	Message string
	// Temporary=true: Runtime may reconnect and call Watch() again after backoff.
	// Temporary=false: unrecoverable; Runtime must transition the attempt to Failed.
	Temporary bool
}

// JobWatch is returned by JobClient.Watch.
//
// Channel close contract (enforced by the JobClient implementation):
//
//	Happy path:
//	  1. Emit JobEvents including a terminal event.
//	  2. Close Events. Close Errs.
//
//	Watch error path:
//	  1. Send one JobWatchError on Errs.
//	  2. Close Events. Close Errs.
//	  On Temporary=true: Runtime may call Watch() again after backoff.
//	  On Temporary=false: Runtime must transition the attempt to Failed.
//
//	Context cancellation:
//	  Close both Events and Errs without sending a terminal event.
//
// The Runtime must select on both channels concurrently.
// Errs should be buffered with capacity 1 to avoid blocking the producer.
type JobWatch struct {
	Events <-chan JobEvent
	Errs   <-chan JobWatchError // buffered capacity 1
}

// JobSnapshot is a point-in-time view returned by JobClient.Snapshot.
// Used by the Runtime during restart reconciliation.
//
// Reason and Timestamp must be populated when State is terminal so that
// JUMI can record the failure cause without re-watching.
type JobSnapshot struct {
	State   AttemptState
	Reason  string // non-empty when State is a terminal failure
	Message string
	// Timestamp is the observed time of the current state.
	Timestamp time.Time
	// Exists is false if the backend job was not found.
	Exists bool
}

// JobClient is the interface spawner defines for backend operations.
// The implementation lives in JUMI (or any other caller).
//
// spawner does NOT provide a production K8s implementation of this interface.
// The existing spawner K8sDriver/buildJob are legacy/reference only and
// must NOT be extended with new features.
//
// JobClient responsibilities:
//   - Build the backend job spec from JobCreateRequest fields
//   - resource.ParseQuantity for CPU/Memory
//   - Placement → NodeSelector / Affinity / tolerations translation
//   - ServiceAccountName and WorkingDir application
//   - Volume/VolumeMount construction (PVC; HostPath with policy gate)
//   - System label injection (e.g. "spawner.io/attempt-marker")
//   - Normalize backend status into JobEvents
//   - Idempotent Create verified by AttemptMarker
//
// NOT JobClient responsibilities (Runtime):
//   - Retry/backoff on transient API errors
//   - Bounded concurrency
//   - Start/cancel race coordination
//   - AttemptTimeout enforcement
type JobClient interface {
	// Create submits a new job and returns its BackendRef.
	//
	// Idempotency contract:
	//   Same (Namespace, JobName) AND matching AttemptMarker → return existing BackendRef.
	//   Same (Namespace, JobName) AND different AttemptMarker → return ErrJobConflict.
	//
	// Implementation must store req.AttemptMarker as label "spawner.io/attempt-marker".
	// Must never store raw RunID, NodeID, or sample identifiers as K8s labels.
	Create(ctx context.Context, req JobCreateRequest) (BackendRef, error)

	// Watch returns a JobWatch for the given backend resource.
	// If the job is not found at call time, both channels are closed immediately.
	// See JobWatch for the channel close contract.
	Watch(ctx context.Context, ref BackendRef) (JobWatch, error)

	// Delete removes the backend job. Idempotent: NotFound is treated as success.
	Delete(ctx context.Context, ref BackendRef) error

	// Snapshot returns the current state without subscribing to events.
	// Returns Exists=false if the job was not found.
	// Used by the Runtime during restart reconciliation.
	Snapshot(ctx context.Context, ref BackendRef) (JobSnapshot, error)
}
